"""create tables

Revision ID: 26df93473e7e
Revises: 
Create Date: 2024-07-29 14:12:11.660491

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '26df93473e7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
